### PR TITLE
5.8 BelongsTo Relation fix

### PR DESCRIPTION
**Pull request by OzanKurt**

### CODE REVIEW

**Comment by OzanKurt** [comment]
@jarektkaczyk Please merge <3

**Comment by jarektkaczyk** [comment]
@OzanKurt thanks,
could your write a failing test for that too?

**Comment by OzanKurt** [comment]
I don't know what you mean by that. :/

**Comment by jarektkaczyk** [comment]
@OzanKurt 
show me how it's broken in a sample code, that will do :)

thanks!

**Comment by OzanKurt** [comment]
Pretty simple,

```php
// relation -> BelongsTo
Model::joinRelations(['relation'])->get();
```

the code above generates this Exception:

```php
BadMethodCallException
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::getQualifiedForeignKey()
```

I hope this helps.

**Comment by ghost** [comment]
Please add this update, as the implementation is broken in Laravel 5.8.

The change is documented in upgrade guide:
https://laravel.com/docs/5.8/upgrade

**Comment by jarektkaczyk** [comment]
@studmon @OzanKurt tagged https://github.com/jarektkaczyk/eloquence-base/releases/tag/v5.6.3

**Comment by coachops** [comment]
Hi, @jarektkaczyk thanks for the great package. Just to say that this change appears to be breaking for Laravel 5.7. Is not the end of the world as easy to revert but thought perhaps it should go in a major point release?

**Comment by jarektkaczyk** [comment]
thanks, will look into it!

Regards,
Jaroslaw Tkaczyk

SOFTonSOFA :: development with pleasure
from Krakow, in Singapore

**Pull request merged**
